### PR TITLE
tests: remove redundant dune rules

### LINKED ISSUE #35: Tests fail with dune 3.17.0
Running the test suite (`dune runtest`) fails with the following errors:

> Error: No rule found for tests/solveEmpty.output
> -> required by alias tests/runtest in tests/dune:15
> Error: No rule found for tests/standalone_minimal_maximization.output
> -> required by alias tests/runtest in tests/dune:22
> Error: No rule found for tests/standalone_minimal.output
> -> required by alias tests/runtest in tests/dune:32
> Error: No rule found for tests/standalone_test_strict_bounds.output
> -> required by alias tests/runtest in tests/dune:42

Removing the `rules` stanza from `tests/dune` seems to fix the issue.

### PR DESCRIPTION
**Pull request by vbgl**
These rules are broken with dune 3.17.0

Fixes #35.

### CODE REVIEW

**Comment by bclement-ocp** [comment]
Thanks for the report and suggested fix! I don't really understand what changed in dune 3.17 to break this, and I will look into it, but you might know — you are saying these rules are redundant ; are they automatically introduced by the `test` rules now?

**Comment by vbgl** [comment]
Sorry, I don’t have any answer to your questions.

**Comment by Halbaroth** [comment]
Thanks for reporting the issue. It seems that Dune automatically generates these rules according to the documentation of `tests`:
https://dune.readthedocs.io/en/stable/reference/dune/test.html
> This defines an executable named mytest.exe that will be executed as part of the runtest alias. If the directory also contains 
> an expect_test.expected file, then expect_test will be used to define an expect test. That is, the test will be executed and its 
> output will be compared to expect_test.expected. 

This stanza has been added several years ago: https://github.com/ocaml/dune/pull/822. There is no relation with the latest release but it seems that we did not use correctly this stanza. I guess Dune does not realize that the rule below needs to run after `tests`.

```dune
(rule
 (alias runtest)
 (action
  (diff solveEmpty.expected solveEmpty.output)
 )
)
```

I checked that tests are still running with your patch with Dune 3.16 and 3.17.

**Review by Halbaroth — APPROVED** [review]

**Comment by vbgl** [comment]
Thanks!

**Pull request merged**
